### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ariG23498** [ml-gde/jflux#1]
Roadmap:
- [x] #2
- [x] Port the model weights from Torch to Flax (#15)
- [x] Tests on output shape and numerics (#12 )
- [x] Writing an end to end pipeline (#13)

Some pointers to note:
1. Use the `flax.nnx` API
2. Be very careful with the `dtype` mismatches -- probably will cause tests to fail
3. Strengthen reproducibility with JAX's PRNG apis
